
modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="betterparagliders"
version="${file.jarVersion}"
displayName="Better Paragliders"
logoFile="betterparagliders.png"
credits="Thanks for this example mod goes to Java"
authors="CravenCraft"

description='''
A compat mod that brings Paraglider's stamina system to Better Combat.
'''

[[dependencies.betterparagliders]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.betterparagliders]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.betterparagliders]]
    modId="bettercombat"
    mandatory=true
    versionRange="[1.7.1+1.19]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.betterparagliders]]
    modId="paraglider"
    mandatory=true
    versionRange="[1.7.0.5]"
    ordering="AFTER"
    side="BOTH"