
modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
[[mods]]
modId="betterparagliders"
version="${file.jarVersion}"
displayName="Better Paragliders"
logoFile="betterparagliders.png"
credits="Thanks for this example mod goes to Java"
authors="CravenCraft"

description='''
A compat mod that brings Paraglider's stamina system to Better Combat.
'''

[[dependencies.betterparagliders]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.betterparagliders]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.betterparagliders]]
    modId="bettercombat"
    mandatory=true
    versionRange="[1.8.5+1.20.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.betterparagliders]]
    modId="paraglider"
    mandatory=true
    versionRange="[20.1.3]"
    ordering="AFTER"
    side="BOTH"